### ISSUE TITLE
Constrain video length?

### ISSUE THREAD

**Issue by Trott** [Trott/musicroutes-playlist-generator#72]
Perhaps constraining the video length in the search options will result in fewer whole album videos and more videos of the song sought?

**Comment by Trott** [comment]
Unfortunately, videoDuration filtering in YouTube API v3 search is crude. You can restrict results to videos that are less than 4 minutes long, or 4-20 minutes long, but not both. We'd want to include both and only exclude videos longer than 20 minutes. With the current API, that would require two searches.

**Comment by Radu-Raicea** [comment]
3 years later, they still don't provide a fix to this...
